import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Home: NextPage = () => {
  const [inputText, setInputText] = useState("");

  const assignOnChange = (event: any) => {
    setInputText(event.target.value);
  };

  const copyTextToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).then(
      () => {
        console.log("'" + text + "'" + "was coppied!");
      },
      (err) => {
        console.log(err + ": Could not copy");
      }
    );
  };

  const convertText = (text: string) => {
    const isEmpty = text === "";
    return isEmpty ? "" : text.split("").join("゛") + "゛";
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>nyanchu-megaphone</div>
      <textarea value={inputText} onChange={assignOnChange} />
      <textarea defaultValue={convertText(inputText)} />
      <button onClick={() => copyTextToClipboard(convertText(inputText))}>
        コ゛ピ゛ー゛
      </button>
    </div>
  );
};

export default Home;
